// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Album struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Artist      *Artist `json:"artist"`
	ReleaseDate string  `json:"releaseDate"`
	CoverArt    *string `json:"coverArt,omitempty"`
	Genre       *Genre  `json:"genre,omitempty"`
}

type Artist struct {
	ID               string   `json:"id"`
	Name             string   `json:"name"`
	Bio              *string  `json:"bio,omitempty"`
	ProfileImage     *string  `json:"profileImage,omitempty"`
	Verified         bool     `json:"verified"`
	MonthlyListeners int32    `json:"monthlyListeners"`
	Albums           []*Album `json:"albums"`
}

type Genre struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description *string  `json:"description,omitempty"`
	Albums      []*Album `json:"albums"`
}

type Link struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Address string `json:"address"`
	User    *User  `json:"user"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NewLink struct {
	Title   string `json:"title"`
	Address string `json:"address"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Query struct {
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
